php-http/psr7-integration-tests

src/ServerRequestIntegrationTest.php
src/StreamIntegrationTest.php

| BC breaks?      | yes
| Related tickets | partially #7 
- Fixes an issue where an integer is set to ServerRequest::withParsedBody which should cause an InvalidArgumentException as it is defined like:
- `@param null|array|object $data`
- `@throws \InvalidArgumentException if an unsupported argument type is provided.`
- Also added invalid Testcases for this
- Updated StreamTest::testToStringReadOnlyStreams to use current file for test instead of remote
- so we do not depend on a remote file and
- the remote file doesn't work here

Update some TestCases with issues

---

composer.json

| New feature?    | no|yes
We should test against Slim-Http instead of the whole Framework. Slim-Http is the Psr-7 implementation from Slim V3 as separate package and will be used from Slim V4 on.
We should not test against the whole framework since it is not just Psr-7.

Use Slim-Http for tests

---

src/StreamIntegrationTest.php

| Related tickets | found in review of slimphp/Slim-Http#32
- the @ suppresses warnings/errors which shoud be omitted
- if a resource is closed it is not a resource anymore, so we can check it using `is_resource`

Better test if a Stream is closed

---

README.md
src/StreamIntegrationTest.php

| Related tickets | n/a
| Documentation   | n/a
A reshuffling of some Stream tests. Tests that require a live internet connection are now grouped together in a PHPUnit `@group` called “internet”. This group
name follows the prior art [set by by Guzzle](https://guzzle3.readthedocs.io/testing/unit-testing.html#group-internet-annotation).
I ran into this when repeatedly testing [Nyholm/psr7](https://github.com/Nyholm/psr7) on a flaky 4G connection, and it bothered me when tests either took really long or threw exceptions.
I am not alone in developing on a non-stellar internet connection. Not to mention people who do development in …

Split of tests requiring live internet connection

---

src/MessageTrait.php

Adding one extra test for `withHeader`.
It doesn’t look like there was a test for empty header values, those are allowed per RFC 7230, see Nyholm/psr7#38.
Happy to update the CHANGELOG when decided that the PR is done.

Test empty header field

---

composer.json

| Related tickets | -
| Documentation   | -
- moved phpunit to require-dev
- updated php version to php5.5 Class name resolution via ::class is not supported in php 5.4
- changed path in script test, composer knows all vendor bins
is much cleaner like this

Some changes in composer.json

---

src/MessageTrait.php
src/RequestIntegrationTest.php
src/ResponseIntegrationTest.php
src/ServerRequestIntegrationTest.php
src/StreamIntegrationTest.php
src/UriIntegrationTest.php

- Use assertSame where it had meaning.
- Use a clone of the objects under testing. This way we ensure that the object has not changed state.
- Added some more assertions.

Improve tests

---

composer.json
src/BaseTest.php
tests/Slim/RequestTest.php
tests/Slim/ResponseTest.php
tests/Slim/ServerRequestTest.php
tests/Slim/StreamTest.php
tests/Slim/UploadedFileTest.php
tests/Slim/UriTest.php

PSR-7 implementation of slimphp has been moved to slim/psr7. slim/http is still existing, but as of release 0.5 this is just providing wrappers around PSR-7 implementations for convenience.

slim/http is now slim/psr7

---

.gitignore
.travis.yml
composer.json
src/MessageTrait.php
src/RequestIntegrationTest.php
src/ResponseIntegrationTest.php
src/ServerRequestIntegrationTest.php
src/StreamIntegrationTest.php
src/UploadedFileIntegrationTest.php

When trying to fix a Slim-Psr7 compatibility issue with PHP 7.4, I ran into a bunch of failing tests due to PHPUnit 7.x not being fully compatible with PHP 7.4. These issues were fixed in PHPUnit 8, but Slim-Psr7 can't be tested with PHPUnit 8 unless this library (which Slim-Psr7 depends on) also supports PHPUnit 8.
Unfortunately it doesn't appear possible to support both PHPUnit 8 and PHPUnit 7/6/5 at the same time when implementing methods like `setUp` that have a void return type. So it may be best to either merge this PR into a branch other than master, or else tag a release, so libraries that don't support PHPUnit 8 can use it as their dependency version instead of dev-master.

Add support for PHPUnit 8

---

.travis.yml
README.md
composer.json
phpunit.xml.dist
tests/Laminas/RequestTest.php
tests/Laminas/ResponseTest.php
tests/Laminas/ServerRequestTest.php
tests/Laminas/StreamTest.php
tests/Laminas/UploadedFileTest.php
tests/Laminas/UriTest.php

As of 2019-12-31 Zendframework was abandoned and moved to Laminas. Nowadays everyone is adding Laminas integrations to their existing Zend ones. I just renamed Zend to Laminas here to be up to date with the current implementation.

Zendframework is now Laminas

---

src/RequestIntegrationTest.php
src/ServerRequestIntegrationTest.php
src/StreamIntegrationTest.php
tests/Guzzle/RequestTest.php
tests/Guzzle/ResponseTest.php
tests/Guzzle/ServerRequestTest.php

Skip test not suitable for guzzle. Replaces #40. The remaining failure will be resolved with https://github.com/guzzle/psr7/pull/317

fix guzzle test suite

---

.travis.yml
composer.json

| Related tickets | N/A
| Documentation   | N/A
Allow installing on PHP 8.

Allow installing on PHP 8.

---

src/MessageTrait.php
src/UploadedFileIntegrationTest.php

| Deprecations?   | yes
| Related tickets | follow-up to https://github.com/php-http/psr7-integration-tests/pull/45
| Documentation   | TBD
In https://github.com/php-http/psr7-integration-tests/pull/45 compatibility with phpunit 9.3 was declared
But 9.3 throws warnings now on usage of `assertRegExp()` replaced with `assertMatchesRegularExpression()` in phpinit 9.1 
Ref https://phpunit.readthedocs.io/en/9.1/assertions.html#assertmatchesregularexpression 
Testing https://github.com/laminas/laminas-diactoros/pull/46 travis reports this warnings because it using php 8 (nightly) so composer resolves phpunit to 9.3
Also package tests reports the same …

Replace deprecated assertRegExp() with assertMatchesRegularExpression()

---

src/UploadedFileIntegrationTest.php

| New feature?    | no|yes
| BC breaks?      | no|yes
| Deprecations?   | no|yes
| Related tickets | -
This PR include changes to UploadedFileIntegrationTest.php by using sys_temp_dir() rather than mkdir().
When using this repo as a dependency for testing against an implementation, running tests create an unwanted ".tmp" directory.

Use sys_temp_dir() instead of mkdir in UploadedFileIntegrationTest

---

src/UriIntegrationTest.php

| Related tickets | 
| Documentation   |
I've seen implementation violating the spec RFC 3986, e.g. https://github.com/zendframework/zend-diactoros/commit/68fc7424a66735926589dbaf74c0659c09e75764
So let's add a proper test for this.

Add test for URI with multiple slashes

---

src/UriIntegrationTest.php

| Related tickets | -
This PR allows marking the [`testPathWithMultipleSlashes`](https://github.com/php-http/psr7-integration-tests/blob/master/src/UriIntegrationTest.php#L230) method skipped.

Allow marking `testPathWithMultipleSlashes` skipped

---

composer.json
src/BaseTest.php
tests/Guzzle/StreamTest.php
tests/Guzzle/UploadedFileTest.php
tests/RingCentral/StreamTest.php

This allows one to use current guzzlehttp/psr7 for tests.

Support recent guzzlehttp/psr7

---

CHANGELOG.md
src/RequestIntegrationTest.php
src/UriIntegrationTest.php

| BC breaks?      | potentially
| Related tickets | fixes laminas/laminas-diactoros#74, closes laminas/laminas-diactoros#77
| Documentation   | (TBD)
Per an [issue created for Diactoros](https://github.com/laminas/laminas-diactoros/issues/74) its [related pull request](https://github.com/laminas/laminas-diactoros/pull/77), and the discussion to that pull request, this patch does the following:
- It modifies `testPathWithMultipleSlashes()` to only validate that multiple slashes _not at the beginning_ of a path are retained intact.
- It adds `testProperlyTrimsLeadingSlashesToPreventXSS()`, which validates that when multiple leading slashes are present …

Modify multiple slash in URI path detection

---

.travis.yml
composer.json

| BC breaks?      | yes
| Deprecations?   | yes
| Related tickets | -
| Documentation   | -
This PR drops support for PHP 7.x and bumps dependencies accordingly.
This will probably require a major version release. The repositories that support PHP 7.x can continue to use the current version (`^1.2`).
PHP versions 7.x have reached their end of life. PHP 8.0 and 8.1 are only versions that are currently supported. PHP 8.2 will be released in a week.

Build with PHP 8.0 and 8.1

---

src/RequestIntegrationTest.php
src/ServerRequestIntegrationTest.php

| Related tickets | #57 
| Documentation   | 
Make `ServerRequestIntegrationTest` extend `RequestIntegrationTest`.
This will make sure that no Server Request implementations break the behaviours inherited from Request.
In the PSR, `ServerRequestInterface` extends `RequestInterface`.
This means that a Server Request implementation should also behave like a `RequestInterface`.
Given the current structure of the tests, it is not easy to verify this.
`RequestIntegrationTest` and `ServerRequestIntegrationTest` both extend `BaseTest`.
In order to check if a Server Request behaves like both a Server Request and a Request, we currently …

make request tests run for server request too #57

---

CHANGELOG.md

This also adds all changes since v1.0.0 to the CHANGELOG
| Related tickets | none
| Documentation   | none
This PR adds CHANGELOG for all versions since v1.0.0 as requested in https://github.com/php-http/psr7-integration-tests/pull/65#discussion_r1157184264

Introduce keep-a-changelog

---

CHANGELOG.md
src/UriIntegrationTest.php

| Related tickets | fixes #61
There are two new tests added which verify that the `UriInterface#withUserInfo` can handle both already encoded and reserved characters.
Due to the interoperability idea, all PSR-7 implementations should behave the same. I recently found out that not all PSR-7 implementations do behave the same and thus I ended up having invalid URIs.

Introduce `userInfo` encoding tests

---

src/UriIntegrationTest.php

Adds a test case for URIs with an authority part that consists of a `host` and `port` only
| New feature?    | yes (depends on whether you're seeing this as a feature)
| Related tickets | 
| Documentation   | 
I've added an additional test case for URIs with an authority that consists of a host and port only.
This was a combination that was missing from the existing test cases.
Not sure whether this is an update worth mentionable in the changelog. I've decided not to.

Adds additional authority test case
